import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/assets/Fontawesome-Pro/fonts/brands.css"
import "@/assets/Fontawesome-Pro/fonts/chisel-regular.css"
import "@/assets/Fontawesome-Pro/fonts/duotone-light.css"
import "@/assets/Fontawesome-Pro/fonts/duotone-regular.css"
import "@/assets/Fontawesome-Pro/fonts/duotone.css"
import "@/assets/Fontawesome-Pro/fonts/etch-solid.css"
import "@/assets/Fontawesome-Pro/fonts/fontawesome.css"
import "@/assets/Fontawesome-Pro/fonts/jelly-duo-regular.css"
import "@/assets/Fontawesome-Pro/fonts/jelly-fill-regular.css"
import "@/assets/Fontawesome-Pro/fonts/jelly-regular.css"
import "@/assets/Fontawesome-Pro/fonts/light.css"
import "@/assets/Fontawesome-Pro/fonts/notdog-duo-solid.css"
import "@/assets/Fontawesome-Pro/fonts/notdog-solid.css"
import "@/assets/Fontawesome-Pro/fonts/regular.css"
import "@/assets/Fontawesome-Pro/fonts/sharp-duotone-light.css"
import "@/assets/Fontawesome-Pro/fonts/sharp-duotone-regular.css"
import "@/assets/Fontawesome-Pro/fonts/sharp-duotone-solid.css"
import "@/assets/Fontawesome-Pro/fonts/sharp-duotone-thin.css"
import "@/assets/Fontawesome-Pro/fonts/sharp-light.css"
import "@/assets/Fontawesome-Pro/fonts/sharp-regular.css"
import "@/assets/Fontawesome-Pro/fonts/sharp-solid.css"
import "@/assets/Fontawesome-Pro/fonts/sharp-thin.css"
import "@/assets/Fontawesome-Pro/fonts/slab-press-regular.css"
import "@/assets/Fontawesome-Pro/fonts/slab-regular.css"
import "@/assets/Fontawesome-Pro/fonts/solid.css"
import "@/assets/Fontawesome-Pro/fonts/thumbprint-light.css"
import "@/assets/Fontawesome-Pro/fonts/utility-duo-semibold.css"
import "@/assets/Fontawesome-Pro/fonts/utility-fill-semibold.css"
import "@/assets/Fontawesome-Pro/fonts/utility-semibold.css"
import "@/assets/Fontawesome-Pro/fonts/whiteboard-semibold.css"
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
