import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/assets/Fontawesome-Pro/fonts/brands.css"
import "@/assets/Fontawesome-Pro/fonts/chisel-regular.css"
import "@/assets/Fontawesome-Pro/fonts/duotone-light.css"
import "@/assets/Fontawesome-Pro/fonts/duotone-regular.css"
import "@/assets/Fontawesome-Pro/fonts/duotone.css"
import "@/assets/Fontawesome-Pro/fonts/etch-solid.css"
import "@/assets/Fontawesome-Pro/fonts/fontawesome.css"
import "@/assets/Fontawesome-Pro/fonts/light.css"
import "@/assets/Fontawesome-Pro/fonts/regular.css"
import "@/assets/Fontawesome-Pro/fonts/solid.css"



import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import  TimeContext  from "@/state/timeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-[#f8fafc] flex flex-col">
        <Navbar />
        <TimeContext>
          {children}
        </TimeContext>
        <Footer/>
      </body>
    </html>
  );
}
